site_name: github-heroku-attack-rabbits
site_url: https://pages.charlesreid1.com/github-heroku-attack-rabbits
repo_name: charlesreid1/github-heroku-attack-rabbits
repo_url: https://git.charlesreid1.com/charlesreid1/github-heroku-attack-rabbits
edit_uri: ""


# give a title for each page
pages:
  - 'Index' : 'index.md'


copyright: 'Copyright &copy; 2018 Charles Reid, released under the <a href="https://git.charlesreid1.com/charlesreid1/github-heroku-attack-rabbits/src/branch/master/LICENSE">WTFPL</a>.<br /><br />Many Bothans died to bring us this documentation.<br /><br />'

docs_dir: docs
site_dir: site

theme:

  name: null
  custom_dir: 'mkdocs-material/material'

  # pretty colors! see https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
  palette:
    primary: 'grey'
    accent: 'grey'
  
  # fun logos! see https://material.io/icons/
  logo:
    icon: 'lock'

  font:
    text: 'Questrial'
    code: 'Roboto Mono'

# this will add docs/css/custom.css to all your docs
extra_css:
  - css/custom.css
